# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:34
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_test_reports(apps, schema):
    call_command('loaddata', '--verbosity', '0', 'test_reports')


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_load_test_users'),
    ]

    operations = [
        migrations.RunPython(load_test_reports)
    ]
